# -*- coding: utf-8 -*-
"""Assignment1_simple_interest.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SWpek92TMwVI1i9HBjCbbzlODJpUsnaP
"""

#simple interest
P=int(input())
T=int(input())
R=int(input())
SI=P*T*R/100
print(SI)