# -*- coding: utf-8 -*-
"""Assignment1_area_of_circle

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hxs9eClbnu2GFuOWyOzKa1tYawzZHTl6
"""

#area of circle
r=int(input())
aof=3.14*r*r
print(aof)