# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t__UAUp1-d7a0dctmB7aY8a-lUP3IwAd
"""

#convert celsius to Fahreinhet
C=float(input())
F=C*1.8000+32.00
print("Fahreinhet scale is",F)