# -*- coding: utf-8 -*-
"""Assignment1_area_of_triangle

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UWiHQzIgF4EMos_rGUeo8OwBGlCanPtW
"""

#area of triangle
b=int(input())
h=int(input())
aof=0.5*b*h
print(aof)