# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kv1rmIjtAjWv-iVOk6KgMhy5lW7S5jEe
"""

#swap of two numbers
#before swap
a=2
b=3
c=a
a=b
b=c
print("after swap",a,b)