# -*- coding: utf-8 -*-
"""Assignment1_perimeter_of_square

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z6XNvSOnRQF4tCQi35ZWNVXGtyP-PbJF
"""

#perimeter of square
a=int(input())
pos=4*a
print(pos)