# -*- coding: utf-8 -*-
"""Assignment1_area_of _rectangle

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ir2X7810z2VqYrvP8tvud_ihT9h1qRUW
"""

#area of rectangle
L=int(input())
B=int(input())
aor=L*B
print(aor)