# -*- coding: utf-8 -*-
"""Assignment1_simple calculator.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hz6UFaXxWv3TtI21-Fhwe52yf_QmmpIW
"""

#simple calculator
a=int(input())
b=int(input())
print("Addition=",a+b)
print("subtraction=",a-b)
print("multiplication=",a*b)
print("Division=",a/b)
print("modulus=",a%b)
print("floor Division",a//b)
print("exponetof=",a**b)