# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ct1BAlTbgnkr5O-fPZ9qWeJLIa72GmHg
"""

#circumference of circle
r=int(input())
coc=2*3.14*r
print(coc)